/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.Filter.digitFilter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author fahmi
 */
public class PertambahanDuaAngka extends javax.swing.JFrame {

    /**
     * Creates new form PertambahanDuaAngka
     */
    public PertambahanDuaAngka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        angka1TextField = new javax.swing.JTextField();
        angka2TextField = new javax.swing.JTextField();
        hasilTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        aksiLable = new javax.swing.JLabel();
        ButtonTambah = new javax.swing.JButton();
        ButtonKurang = new javax.swing.JButton();
        ButtonKali = new javax.swing.JButton();
        ButtonBagi = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fahmi Kalkulator Sederhana");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        angka1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angka1TextFieldKeyTyped(evt);
            }
        });

        angka2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angka2TextFieldKeyTyped(evt);
            }
        });

        hasilTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hasilTextFieldKeyTyped(evt);
            }
        });

        jLabel1.setText("=");

        ButtonTambah.setText("Tambah");
        ButtonTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonTambahMouseReleased(evt);
            }
        });

        ButtonKurang.setText("Kurang");
        ButtonKurang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonKurangMouseReleased(evt);
            }
        });

        ButtonKali.setText("Kali");
        ButtonKali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonKaliMouseReleased(evt);
            }
        });

        ButtonBagi.setText("Bagi");
        ButtonBagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonBagiMouseReleased(evt);
            }
        });

        ButtonClear.setText("Clear");
        ButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonClearMouseReleased(evt);
            }
        });

        ButtonExit.setText("Exit");
        ButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonExitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(angka1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aksiLable, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(angka2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ButtonTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonKurang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonBagi, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonExit)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angka1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(aksiLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTambah)
                    .addComponent(ButtonKurang)
                    .addComponent(ButtonKali)
                    .addComponent(ButtonBagi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonClear)
                    .addComponent(ButtonExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTambahMouseReleased
        // TODO add your handling code here:
        double hasil = Double.parseDouble(angka1TextField.getText()) + Double.parseDouble(angka2TextField.getText());
        aksiLable.setText("+");
        hasilTextField.setText(hasil + "");
    }//GEN-LAST:event_ButtonTambahMouseReleased

    private void ButtonClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonClearMouseReleased
        // TODO add your handling code here:
        aksiLable.setText(null);
        hasilTextField.setText("");
        angka1TextField.setText("");
        angka2TextField.setText("");
    }//GEN-LAST:event_ButtonClearMouseReleased

    private void ButtonExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonExitMouseReleased

    private void ButtonKurangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonKurangMouseReleased
        // TODO add your handling code here:
        double hasil = Double.parseDouble(angka1TextField.getText()) - Double.parseDouble(angka2TextField.getText());
        aksiLable.setText("-");
        hasilTextField.setText(hasil + "");
    }//GEN-LAST:event_ButtonKurangMouseReleased

    private void ButtonKaliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonKaliMouseReleased
        // TODO add your handling code here:
        double hasil = Double.parseDouble(angka1TextField.getText()) * Double.parseDouble(angka2TextField.getText());
        aksiLable.setText("x");
        hasilTextField.setText(hasil + "");
    }//GEN-LAST:event_ButtonKaliMouseReleased

    private void ButtonBagiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBagiMouseReleased
        // TODO add your handling code here:
        double hasil = Double.parseDouble(angka1TextField.getText()) / Double.parseDouble(angka2TextField.getText());
        aksiLable.setText(":");
        hasilTextField.setText(hasil + "");
    }//GEN-LAST:event_ButtonBagiMouseReleased

    private void angka1TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angka1TextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) ||
                (c == KeyEvent.VK_BACK_SPACE) ||
                (c == KeyEvent.VK_DELETE))
                )) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Cuma Bisa DiMasukan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_angka1TextFieldKeyTyped

    private void angka2TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angka2TextFieldKeyTyped
        // TODO add your handling code here:        
        angka1TextFieldKeyTyped(evt);
    }//GEN-LAST:event_angka2TextFieldKeyTyped

    private void hasilTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hasilTextFieldKeyTyped
        digitFilter(evt);
    }//GEN-LAST:event_hasilTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PertambahanDuaAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBagi;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonKali;
    private javax.swing.JButton ButtonKurang;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JLabel aksiLable;
    private javax.swing.JTextField angka1TextField;
    private javax.swing.JTextField angka2TextField;
    private javax.swing.JTextField hasilTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
